language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly

before_script:
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
